local basics = require 'develop.basics'

print '----------------------------------------'
basics.describe_test 'develop.testing.dict_tests'
basics.describe_test 'develop.testing.list_tests'
basics.describe_test 'develop.testing.stack_tests'
print '----------------------------------------'
basics.describe_fuzz 'develop.fuzzing.dict_fuzz'
basics.describe_fuzz 'develop.fuzzing.list_fuzz'
basics.describe_fuzz 'develop.fuzzing.stack_fuzz'
print '----------------------------------------'
require 'develop.benchmarks.dict_bmarks'
print '----------------------------------------'
require 'develop.benchmarks.list_bmarks'
print '----------------------------------------'
require 'develop.benchmarks.stack_bmarks'
print '----------------------------------------'
require 'develop.benchmarks.utilities.djb2_bmarks'
print '----------------------------------------'
require 'develop.benchmarks.utilities.nummix_bmarks'
print '----------------------------------------'
require 'develop.benchmarks.utilities.popcount32_bmarks'
print '----------------------------------------'
require 'develop.benchmarks.utilities.pow2_bmarks'
print '----------------------------------------'

print 'All tests passed.'
